import type { Metadata } from "next";
import "../styles/globals.scss";
import { montserrat, poppins } from "@/fonts";
import StateContextProvider from "@/context/StateCtx";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Mr Grace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateContextProvider>
        <body className={`${montserrat.className} ${poppins.variable}`}>
          {children}
          <Toaster />
        </body>
      </StateContextProvider>
    </html>
  );
}
